# Generated by Django 5.0.1 on 2024-03-21 19:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_batch_student_teacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="batch",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="batch",
        ),
        migrations.RemoveField(
            model_name="student",
            name="user",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="user",
        ),
        migrations.DeleteModel(
            name="Batch",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
        migrations.DeleteModel(
            name="Teacher",
        ),
    ]
