# Generated by Django 5.0.1 on 2024-04-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_batch_teacher_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="rollno",
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
