# Generated by Django 5.0.1 on 2024-04-21 18:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_attendance_marks"),
    ]

    operations = [
        migrations.RenameField(
            model_name="marks",
            old_name="student",
            new_name="user",
        ),
    ]
