# Generated by Django 5.0.1 on 2024-04-22 06:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_studentmessage_teachermessage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudentMessage",
        ),
        migrations.DeleteModel(
            name="TeacherMessage",
        ),
    ]
