# Generated by Django 5.0.1 on 2024-04-23 18:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_studentmessage_teachermessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teachermessage",
            name="user",
        ),
        migrations.DeleteModel(
            name="StudentMessage",
        ),
        migrations.DeleteModel(
            name="TeacherMessage",
        ),
    ]
